name: scan
on:
  push:
    branches:
      - 'master'
jobs:
  container:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: "pyama86"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_API: "https://api.github.com/"
    container:
      image: ghcr.io/pyama86/github-image-scaner:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: |
          cp config.yml.sample /opt/scaner/config.yml
          cd /opt/scaner
          ls -ltr 
          bundle exec ruby run.rb
